[tool.poetry]
name = "definitive-openassistants-fastapi"
version = "0.0.14"
description = ""
authors = ["Rick Lamers <ricklamers@gmail.com>"]
readme = "README.md"
packages = [{ include = "openassistants_fastapi" }, { include = "openassistants_fastapi/py.typed" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
sse-starlette = "^1.8.2"
fastapi = "^0.109.2"
langchain = "^0.0.352"
starlette = "0.36.3"

[tool.poetry.group.test.dependencies]
ruff = "^0.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
